import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";


const DM_SANS=DM_Sans({
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${DM_SANS.className} h-full antialiased`}
    >

      <body className="min-h-full flex  flex-col">

        {children}</body>
    </html>
  );
}
